## HPC EX 1

In [53]:
import os
import numpy as np
import scipy
# If you have matplotlib 1.5 or higher, we can use live plotting!
import matplotlib as mpl
if float(mpl.__version__[:3]) >= 1.5:
    %matplotlib notebook
else:
    %matplotlib inline
    
import matplotlib.pyplot as plt
import time

def per_shift(mat):
    rMax = mat.shape[0]
    cMax = mat.shape[1]
    matShift = mat.copy()
    for q in range(matShift.shape[2]):
        # channel directions
        
        # center (q==0)
        # stays constant
        
        if q == 1:
            # east
            matShift[:, :, q] = np.roll(matShift[:, :, q], shift=1, axis=1)
            continue
        if q == 2:
            matShift[:, :, q] = np.roll(matShift[:, :, q], shift=-1, axis=0)
            continue
        if q == 3:
            matShift[:, :, q] = np.roll(matShift[:, :, q], shift=-1, axis=1)
            continue
        if q == 4:
            matShift[:, :, q] = np.roll(matShift[:, :, q], shift=1, axis=0)
            continue
        if q == 5:
            arr = matShift[:, :, q]
            tmpRow = arr[0,:]
            tmpRow = np.roll(tmpRow, shift=1)
            tmpCol = arr[:,arr.shape[1]-1]
            tmpCol = np.roll(tmpCol, shift=-1)
            
            matShift[:-1, 1:, q] = mat[1:, :-1, q]
            
            matShift[arr.shape[0]-1, :, q] = tmpRow
            matShift[:, 0, q] = tmpCol
            continue
        if q == 6:
            arr = matShift[:, :, q]
            tmpRow = arr[0,:]
            tmpRow = np.roll(tmpRow, shift=-1)
            tmpCol = arr[:,0]
            tmpCol = np.roll(tmpCol, shift=-1)
            
            matShift[:-1, :-1, q] = mat[1:, 1:, q]
            
            matShift[arr.shape[0]-1, :, q] = tmpRow
            matShift[:, arr.shape[1]-1, q] = tmpCol
            continue
        if q == 7:
            arr = matShift[:, :, q]
            tmpRow = arr[arr.shape[0]-1,:]
            tmpRow = np.roll(tmpRow, shift=-1)
            tmpCol = arr[:,0]
            tmpCol = np.roll(tmpCol, shift=1)
            
            matShift[1:, :-1, q] = mat[:-1, 1:, q]
            
            matShift[0, :, q] = tmpRow
            matShift[:, arr.shape[1]-1, q] = tmpCol
            continue
        if q == 8:
            arr = matShift[:, :, q]
            tmpRow = arr[arr.shape[0]-1,:]
            tmpRow = np.roll(tmpRow, shift=1)
            tmpCol = arr[:,arr.shape[1]-1]
            tmpCol = np.roll(tmpCol, shift=1)
            
            matShift[1:, 1:, q] = mat[:-1, :-1, q]
            
            matShift[0, :, q] = tmpRow
            matShift[:, 0, q] = tmpCol
            
    return matShift

rows = 4
cols = 5
q = 9
timesteps = 10

latt = np.zeros((rows, cols, q), dtype = float)
# initial lattice occupation
ch = 5
latt[1, 4, ch] = 1.0
print(latt[:,:,ch], '\n')

for t in range(timesteps):
    latt = per_shift(latt)
    print(latt[:,:,ch], '\n')
    



[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]] 

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0

In [34]:
d = np.arange(20).reshape((4,5))
last = 19
mask = (d == last)
idx = np.indices(d.shape)
print(d)
print(d.diagonal(4).shape[0])

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False  True]]
1


In [ ]:
# Plotting code:
fig, ax = plt.subplots(1, 1)
ax.set_title('Training progress')
ax.set_xlim([0, n_epochs])
ax.set_ylim([0, 0.5])
ax.set_xlabel('Epoch')
ax.set_ylabel('Error')

def plot(ax):
    if ax.lines:
        ax.lines[0].set_ydata(training_loss)
        ax.lines[1].set_ydata(valid_loss)
        ax.set_ylim([0,  0.2])
    else:
        ax.plot(training_loss, c='b', label='Training loss')
        ax.plot(valid_loss, c='m', label='Validation loss')
        ax.legend(loc='lower left')
    fig.canvas.draw()
# -- end of plotting code
  

# The training loop
for i in range(n_epochs):
    start = time.time()
    
    
    # Measure the time it took to perform the training in this epoch
    epoch_time[i] = time.time() - start
    
    
    # Update the plot
    if i % update_plot == 0 or i == n_epochs - 1:
        plot(ax)
        

print('\tTraining duration: {:.3f}s'.format(np.sum(epoch_time)))