In [3]:
import numpy as np

def shift_latt(latt):
    
    grid = latt
        
    # center (0,0)
    # stays constant
        
    # east (0,1)
    ch = 1
    grid[:, :, ch] = np.roll(grid[:, :, ch], shift=1, axis=1)
        
    # north (-1, 0)
    ch = 2
    grid[:, :, ch] = np.roll(grid[:, :, ch], shift=-1, axis=0)
        
    # west (0, -1)
    ch = 3
    grid[:, :, ch] = np.roll(grid[:, :, ch], shift=-1, axis=1)
        
    # south (1, 0)
    ch = 4
    grid[:, :, ch] = np.roll(grid[:, :, ch], shift=1, axis=0)
        
    # north-east(-1, 1)
    ch = 5
    grid[:, :, ch] = np.roll(np.roll(grid[:, :, ch], shift=-1, axis=0), shift=1, axis=1)
        
    # north-west(-1, -1)
    ch = 6
    grid[:, :, ch] = np.roll(np.roll(grid[:, :, ch], shift=-1, axis=0), shift=-1, axis=1)
        
    # south-west(1, -1)
    ch = 7
    grid[:, :, ch] = np.roll(np.roll(grid[:, :, ch], shift=1, axis=0), shift=-1, axis=1)
        
    # south-east(1, 1)
    ch = 8
    grid[:, :, ch] = np.roll(np.roll(grid[:, :, ch], shift=1, axis=0), shift=1, axis=1)
            
    return grid


'''
def optimierung(mat):
    
    matShift = mat
    
    c = np.array([[0, 0, -1, 0, 1, 1, -1, -1, 1], [0, -1, 0, 1, 0, -1, -1, 1, 1]])
    #c1 = np.array([[0, 1, 0, -1, 0, 1, -1, -1, 1], [0, 0, 1, 0, -1, 1, 1, -1, -1]])
    
    # Funktionieren nicht mit der Schleife, da i sonst auserhalb des Arrays zugreift
    #c2 = np.array([[0,0], [1,0], [0,1], [-1,0], [0,-1], [1,1], [-1,1], [-1,-1], [1,-1]])
    #c3 = np.array([[0,0], [0,1], [-1,0], [0,-1], [1,0], [-1,1], [-1,-1], [1,-1], [1,1]])

    # von 1 bis 8 für die Channels
    for i in range (1,9):
        print (i)
        print (c[1,i])
        print (c[0,i])
        matShift = np.roll(np.roll(matShift[:, :, i], shift=c[1,i], axis=0), shift=c[0,i], axis=1)
    return matShift
'''

def sum_occ(mat):
    occ = np.sum(mat, axis=2, dtype=float)
    return occ



def calc_j(c, mat):
    j = np.dot(mat, c)
    #j = np.einsum('rowscolsq, ai->rowscolsa', mat, c) -> ?
    return j


def calc_avg_vel(rho, j):
    
    u = j / rho.reshape(rows, cols, 1)
    #u1 = (j.T / rho.T).T
    return u

def calc_equilibrium(rho, u, c1):
    w = np.zeros((1,9), dtype=float)
    w = [4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36, 1/36]
    
    f_eq = np.zeros((1,9), dtype=float)
    
    f_eq = w * rho (1 + u.dot(c1.T) * + 3/2 (u.dot(c1.T))**2 - 3/2 (u)**2)
    
    return f_eq


rows = 3
cols = 3
q = 9
timesteps = 5

c = np.array([[0, 0, -1, 0, 1, -1, -1, 1, 1], [0, 1, 0, -1, 0, 1, -1, -1, 1]])

c1 = np.array([[0,0], [0,1], [-1,0], [0,-1], [1,0], [-1,1], [-1,-1], [1,-1], [1,1]])

latt = np.zeros((rows, cols, q), dtype = float)


# initial lattice occupation
latt[:,:,0] = 4 / 9
latt[:,:,1] = 1 / 9
latt[:,:,2] = 1 / 9
latt[:,:,3] = 0
latt[:,:,4] = 1 / 9
latt[:,:,5] = 1 / 36
latt[:,:,6] = 1 / 36
latt[:,:,7] = 1 / 36
latt[:,:,8] = 1 / 36


rho = sum_occ(latt)
print(rho, '\n', '\n')

j = calc_j(c1, latt)
print(j[0,0], j[1,1])

u = calc_avg_vel(rho, j)
print(u)

for t in range(timesteps):
    #print(latt[:,:,ch], '\n')
    latt = shift_latt(latt)



f_eq = calc_equilibrium(rho, u, c1)



[[ 0.88888889  0.88888889  0.88888889]
 [ 0.88888889  0.88888889  0.88888889]
 [ 0.88888889  0.88888889  0.88888889]] 
 

[ 0.          0.11111111] [ 0.          0.11111111]
[[[ 0.     0.125]
  [ 0.     0.125]
  [ 0.     0.125]]

 [[ 0.     0.125]
  [ 0.     0.125]
  [ 0.     0.125]]

 [[ 0.     0.125]
  [ 0.     0.125]
  [ 0.     0.125]]]


TypeError: 'int' object is not callable

In [4]:
print(calc_j(c1, latt))
print(rho)
print(rho.reshape(rows,cols,1) * u)
w = np.array([4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36], dtype=float)

print(u.shape)
print(c1.shape)
print(w.shape)



[[[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]

 [[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]

 [[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]]
[[ 0.88888889  0.88888889  0.88888889]
 [ 0.88888889  0.88888889  0.88888889]
 [ 0.88888889  0.88888889  0.88888889]]
[[[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]

 [[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]

 [[ 0.          0.11111111]
  [ 0.          0.11111111]
  [ 0.          0.11111111]]]
(3, 3, 2)
(9, 2)
(9,)


In [5]:
import numpy as np
w = np.array([4/9, 1/9, 1/9, 1/9, 1/9, 1/36, 1/36, 1/36, 1/36], dtype=float)
#print(w[0] * rho)
#print(w[0] * rho * (u.dot(c1.T).T))

#print(3/2 * ((u * c)**2) - 3/2 * (u)**2)

#print(w[0] * rho * (u.dot(c1.T).T + 3/2 * ((u.dot(c1.T).T)**2)) - 3/2 * (u)**2)
f0 = (w[0] * rho).dot((1 - 3 / 2 * u**2))
print(f0)
print(f0.shape)

print(c1[0].shape)
print(rho.shape)
print(u.shape)
print
#print(c.T.dot(u.T)).T


f1 = w[1] * rho.dot((1 + c1[1] * u + 3 / 2 * (c1[1] * u**2) - 3 / 2 * c1[1]**2))
f2 = w[2] * rho.dot((1 + c1[2] * u + 3 / 2 * (c1[2] * u**2) - 3 / 2 * (c1[2]**2)))

print(f1.shape)

for i in range(9):
    f = w[i] * rho.dot((1 + c1[i] * u + 3 / 2 * (c1[i] * u**2) - 3 / 2 * (c1[i]**2)))

print((c1[1]*u).shape)
    
print(f)
print(f.shape)

print((c1[1].reshape(2,1,1).T * (u.T).T).shape)

[[[ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]]

 [[ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]]

 [[ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]
  [ 1.18518519  1.15740741]]]
(3, 3, 2)
(2,)
(3, 3)
(3, 3, 2)
(3, 3, 2)
(3, 3, 2)
[[[-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]]

 [[-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]]

 [[-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]
  [-0.03703704 -0.02604167]]]
(3, 3, 2)
(3, 3, 2)
